package marketwatch;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import javax.swing.border.MatteBorder;
import javax.swing.border.TitledBorder;

public class DraggedItem extends javax.swing.JDialog
{    
    public DraggedItem(java.awt.Frame parent, boolean modal,ChartItem item)
    {
        super(parent, modal);
        initComponents();
        initUI(item);
    }
    
    private void initUI(ChartItem item)
    {
        //Some linux systems do not support translucent windows
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gd = ge.getDefaultScreenDevice();
        if(gd.isWindowTranslucencySupported(GraphicsDevice.WindowTranslucency.TRANSLUCENT))
            setOpacity(0.85f);
        
        iconLabel1.setIcon(item.icon1);
        iconLabel2.setIcon(item.icon2);
        var border = (TitledBorder)mainPanel.getBorder();
        border.setTitleFont(item.font);
        border.setTitle(item.title);        
        var matteBorder = (MatteBorder) border.getBorder();
        border.setTitleColor(item.borderColor);
        border.setBorder(new MatteBorder(matteBorder.getBorderInsets(), item.borderColor));
        mainPanel.setBackground(item.bgColor);
        mainPanel.setPreferredSize(item.getSize());
        mainPanel.setMaximumSize(item.getSize());
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainPanel = new javax.swing.JPanel();
        iconLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        iconLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        mainPanel.setBackground(new java.awt.Color(3, 32, 12));
        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 4, 2, 4, new java.awt.Color(255, 255, 0)), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(203, 203, 1))); // NOI18N
        mainPanel.setLayout(new java.awt.GridLayout(1, 3));

        iconLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainPanel.add(iconLabel1);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/item_arrow.png"))); // NOI18N
        mainPanel.add(jLabel3);

        iconLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainPanel.add(iconLabel2);

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLabel1;
    private javax.swing.JLabel iconLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
